### ISSUE TITLE
How to modify the script to support DUO Authentication Proxy?

### ISSUE THREAD

**Issue by AlanTangHKG** [duosecurity/duo_universal_nodejs#19]
May I know how to modify the script that support DUO Authentication Proxy?

For example the DUO Authentication Proxy IP: 10.0.0.1 with port 8080

Thanks!

**Comment by AaronAtDuo** [comment]
@AlanTangHKG Are you trying to use a Duo Authentication Proxy as an HTTP proxy?  I don't believe this library has HTTP Proxy support yet unfortunately.

**Comment by AaronAtDuo** [comment]
No answer
