### ISSUE TITLE
Version string is loaded from package.json

### ISSUE THREAD

**Issue by rfossella** [duosecurity/duo_universal_nodejs#26]
Hi.  So I did a clean **uninstall** of @duosecurity/duo_universal and then did fresh install **v2.0.2**.  I am now running into the same problem where the package.json file cannot be read in constants.js.

I verified this on two separate boxes after fresh install of 2.0.2  The examples package still works as it always did.

Did nothing out of the ordinary, AFAIK, just added it to my package.json and npm install.  Also as a stand-alone install command of package.  Am I missing any step(s)?

**Comment by rfossella** [comment]
BTW, it seems that the previous patch was using const package_json_1 = require("../package.json");

**Comment by rfossella** [comment]
Good news.  The latest fix from package-json-fix2 seems to have worked for me.  Can we complete a new npm version?

**Comment by AaronAtDuo** [comment]
PR was landed and should be released this week

**Comment by rfossella** [comment]
FYI: my testing of v2.0.3 was successful.  Thank you!
