### ISSUE TITLE
Plus characters are mishandled during state generation

### ISSUE THREAD

**Issue by driverjb** [duosecurity/duo_universal_nodejs#28]
Plus characters are mishandled during state generation which results in failure to map the original state to the callback state.

## Description
The utility incorrectly replaces plus signs in the random string generation used for creating a state value. The function call only replaces the first instance of the plus sign. When a string is generated with more than one plus sign, then the resulting string will contain at least one plus sign. When the state is returned by Duo the plus signs are converted to spaces by the handling server, in my case Express, which interprets the plus character as a space in query parameters.

## Expected Behavior
The state value does not contain plus signs.

## Actual Behavior
The state value generated sometimes has plus signs.

## Steps to Reproduce
Generate state values until you get one with a plus sign in it.

**Comment by AaronAtDuo** [comment]
PR merged and should be released this week.
